services:
  db:
    image: postgres:15
    container_name: postgres0
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres0"            
      POSTGRES_PASSWORD: "password123"      
      POSTGRES_DB: "postgresDatabase"           
    ports:
      - "5433:5432"
    volumes:
      - postgres0:/var/lib/postgresql/data

volumes:
  postgres0:
    driver: local