services:
  db:
    image: postgres:15
    container_name: postgres1
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres1"            
      POSTGRES_PASSWORD: "password123"      
      POSTGRES_DB: "postgresDatabase1"           
    ports:
      - "5434:5432"
    volumes:
      - postgres1:/var/lib/postgresql/data

volumes:
  postgres1:
    driver: local