@HostAddress = http://localhost:5247

###
POST {{HostAddress}}/api/event/create
Content-Type: application/json

{
  "EventName": "Work",
  "EventDescription": "call at 12pm",
  "From": "2025-01-31T13:00:00Z",
  "To": "2025-01-31T15:00:00Z"
}
