@HostAddress = http://localhost:5247
@userId = 98591d2f-1e17-4d53-a073-f7bc120a42b6
@id = ec563559-4e7a-452f-9486-9b9527f0b781

###
POST {{HostAddress}}/Users
Content-Type: application/json

{
  "email": "MagicCactus42@proton.me",
  "username": "MagicCactus42",
  "password": "secret123",
  "role": "owner"
}

###
POST {{HostAddress}}/Users/sign-in
Content-Type: application/json

{
  "email": "MagicCactus42@proton.me",
  "password": "secret123"
}

###
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWE0NWI0MC1jZWRmLTRlZDEtYjg3My0wNDY2ZGI3MmZkNTkiLCJ1bmlxdWVfbmFtZSI6ImU1YTQ1YjQwLWNlZGYtNGVkMS1iODczLTA0NjZkYjcyZmQ1OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Im93bmVyIiwibmJmIjoxNzM5OTYzNTQzLCJleHAiOjE3NDAwNDk5NDMsImlzcyI6InBldHByb2plY3QtaXNzdWVyIiwiYXVkIjoicGV0cHJvamVjdC1hdWRpZW5jZSJ9.lEy3_3dij24YL2-AYgG4m3GXWiaF0ps9Lu0B_lbp2V8

###
GET {{HostAddress}}/Users/me
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/Users/{{userId}}
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/Users
Authorization: Bearer {{accessToken}}

###
POST {{HostAddress}}/api/event/create
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "EventName": "gym",
  "EventDescription": "lower body training",
  "From": "2025-02-19T20:00:00Z",
  "To": "2025-02-19T22:00:00Z",
  "CanOverlap": false
}

###
PUT {{HostAddress}}/api/event/change
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "EventId": "ec563559-4e7a-452f-9486-9b9527f0b781",
  "EventName": "gym",
  "EventDescription": "upper body training",
  "From": "2025-02-19T20:00:00Z",
  "To": "2025-02-19T22:00:00Z",
  "CanOverlap": false
}

###
GET {{HostAddress}}/api/event/get
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/api/event/get/{{userId}}
Authorization: Bearer {{accessToken}}

###
DELETE {{HostAddress}}/api/event/delete/{{id}}
Authorization: Bearer {{accessToken}}