@HostAddress = http://localhost:5247
@userId = 06b5604f-6fb1-4436-8996-1dc9ec954576
@id = a693d5a2-9015-48f6-8d19-a35f464eaffc

###
POST {{HostAddress}}/api/users
Content-Type: application/json

{
  "email": "oset@proton.me",
  "username": "oset",
  "password": "secret123",
  "role": "user"
}

###
POST {{HostAddress}}/api/users/login
Content-Type: application/json

{
  "email": "MagicCactus42@proton.me",
  "password": "secret123"
}

###
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWE0NWI0MC1jZWRmLTRlZDEtYjg3My0wNDY2ZGI3MmZkNTkiLCJ1bmlxdWVfbmFtZSI6ImU1YTQ1YjQwLWNlZGYtNGVkMS1iODczLTA0NjZkYjcyZmQ1OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Im93bmVyIiwibmJmIjoxNzQwMzE4NDI0LCJleHAiOjE3NDA0MDQ4MjQsImlzcyI6InBldHByb2plY3QtaXNzdWVyIiwiYXVkIjoicGV0cHJvamVjdC1hdWRpZW5jZSJ9.v1ma5k7e2OXXPv4E3jSYTnX9c9SqRiTUNdshxCsWE1U

###
GET {{HostAddress}}/api/users/me
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/api/users/{{userId}}
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/api/users
Authorization: Bearer {{accessToken}}

###
POST {{HostAddress}}/api/events
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "EventName": "work",
  "EventDescription": "call at 1pm, monday",
  "From": "2025-02-24T13:00:00Z",
  "To": "2025-02-24T13:30:00Z",
  "CanOverlap": false
}

###
PUT {{HostAddress}}/api/events
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "EventId": "2a87855f-c69d-4223-8061-fa6a5b20fb7c",
  "EventName": "gym",
  "EventDescription": "chest + delts workout",
  "From": "2025-02-21T18:00:00Z",
  "To": "2025-02-21T21:00:00Z",
  "CanOverlap": false
}

###
GET {{HostAddress}}/api/events
Authorization: Bearer {{accessToken}}

###
GET {{HostAddress}}/api/events/{{userId}}
Authorization: Bearer {{accessToken}}

###
DELETE {{HostAddress}}/api/events/{{id}}
Authorization: Bearer {{accessToken}}